### ISSUE TITLE
Understanding what state is saved and how

### ISSUE THREAD

**Issue by mcstone** [mcnuttandrew/color-buddy#156]
Palettes and (maybe) some configurations persist to some degree, but I don't understand the model. I think we should include some description in the docs. Can you please explain it to me? Here in the comments would be best.

**Comment by mcnuttandrew** [comment]
I think i disagree that this is something that should be manifested in the docs. it's subject to change and not really relevant to more than 1 or 2 people (me and you). 

But since you asked:
- Anything related to colors is persisted and is connected to undo/redo
- Anything related to configuration is persisted and not connected to undo/redo 
- anything related to selection is not persistent
- examples and lints should be persistent, but i think there's a testing flag accidentally left on

**Comment by mcstone** [comment]
Let me push on this a bit more. Here's the scenario: I need to work on some palettes, which will take several sessions, possibly spread over weeks. In between sessions, I may end up closing the color buddy window, booting the computer, changing platforms, etc.  What can I expect to persist across sessions? What happens if I switch to a new machine/web browser?  Or perhaps the model isn't important, what we need to be focusing on is a way to externalize my palettes and my customizations to the examples and to the lints, so that I don't care about the underlying mechanism.

**Comment by mcnuttandrew** [comment]
Persistence here means that things are saved not in each browser instance. So if i open a new browser (such as using safari rather than firefox) that data will not persist, similarly if i open an incognito tab from my standard browser than it will not persist. Again, i don't think this is something that needs to be documented super deeply (as we may change it), this is more like a 1 line addition in the about tooltip

**Comment by mcnuttandrew** [comment]
Added a note to the about to clarify this, don't think it needs to be clarified further
